"""initial persistence schema

Revision ID: af87e41b0414
Revises: 
Create Date: 2026-08-07 22:35:25.713143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af87e41b0414'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'idempotency_key', name='uq_collection_run_idempotency')
    )
    op.create_index(op.f('ix_collection_runs_dataset_id'), 'collection_runs', ['dataset_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'report_version', 'format', name='uq_export_natural_key')
    )
    op.create_index(op.f('ix_exports_report_id'), 'exports', ['report_id'], unique=False)
    op.create_table('interpretation_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('selector', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interpretation_records_analysis_run_id'), 'interpretation_records', ['analysis_run_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('collection_run_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_type_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_type_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_idempotency_key'), 'analysis_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('report_citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('interpretation_record_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_citations_report_id'), 'report_citations', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_citations_report_id'), table_name='report_citations')
    op.drop_table('report_citations')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_idempotency_key'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_interpretation_records_analysis_run_id'), table_name='interpretation_records')
    op.drop_table('interpretation_records')
    op.drop_index(op.f('ix_exports_report_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_collection_runs_dataset_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
